skeleton html
ffakih5/Travelmate pull request #2
Opened 2021-01-12 11:12 UTC by ffakih5

Added skeleton html. testing pull request

2021-01-12 11:19 UTC, ffakih5 reviewed
approved

2021-01-12 22:50 UTC, malakhim requested changes

2021-01-12 22:50 UTC, malakhim commented on index.html
> +     <h1>
Don't forget to close your `h1`!

```suggestion
     <h1></h1>
```

2021-01-13 06:56 UTC, ffakih5 commented
`

2021-01-13 06:56 UTC, ffakih5 commented
Need to merge

2021-01-13 07:48 UTC, ffakih5 commented
changed to draft

2021-01-13 08:25 UTC, closed without merging